name: Build a Docker image and Push it to ACR
#Based on https://brendanthompson.com/posts/2022/02/using-github-actions-to-publish-container-images-to-azure-container-registry

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

env:
  IMAGE_NAME: ma4c-shortener

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACR_NAME }}/${{ env.IMAGE_NAME }}:latest