name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

env:
  IMAGE_NAME: ma4c-shortener

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Log into registry
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: ${{ secrets.ACR_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}